[package]
name = "rust_image_processing"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
debug = false
panic = "abort"